---
title: "cercospoRa Earliest Epidemic Onset Estimation"
author: "Paul Melloy"
date: "`r Sys.Date()`"
output: html_document
---

## Setup environment  
### Load R libraries  

```{r setup}
library(cercospoRa) 
library(here)
#library(terra)
```

### Read in data  

```{r read_data}
wethr <- read.csv(system.file("extdata", "clean_weather.csv",
                              package = "cercospoRa"))
wethr <- format_weather(wethr,time_zone = "UTC")
```


## Define functions  

### Generate EEEO maps  
```{r genEOmaps}
generate_EO_maps = function(platform, 
                            path = "data", 
                            platform_dir){
  # Directory containing LAI maps
  img_dir <- here::here(path, platform_dir)
  
  # list all files with '.tif file extension
  tif_files <- list.files(img_dir, pattern = ".tif$", full.names = TRUE)

  # Get dates from files
  img_dates <- 
    substr(tif_files,
           regexpr("\\d{8}",tif_files),
           regexpr("\\d{8}",tif_files)+7)
  img_dates <- as.POSIXct(as.Date(img_dates, format = "%Y%m%d"), tz = "UTC")
  
  # Function from Cercospora to read all available LAI maps at different dates
  #  and stack them together in a list
  epidemic_onset_param <-
    read_sb_growth_parameter(
      img_files = tif_files,
      img_dates = img_dates,
      target_res = 10)

  # Use the previously generated list to generate a map of parameters for the pixel-wise sigmoids
  param_rxt <- calc_r_x0(epidemic_onset_param,
                         min_r = 0.02,
                         max_r = 0.05,
                         k = 6)

  # Determine canopy closure dates (date when the sigmoid crosse LAI = 3)
  c_closure <- calc_c_closure(param_rxt,
                              x1 = 1.3,
                              k=6 )

  # Partially fill the function to calculate epidemic onset dates from the 
  #  previously generated CC dates, keeping cultivar susceptibility as the 
  #  only variable parameter.
  calc_epidemic_onset_from_image_different_sus <- 
    function(cultivar_sus){
      # this takes about 20 sec to run
      epidemic_onset_map <- calc_epidemic_onset_from_image(
        start = as.POSIXct("2022-04-25", tz = "UTC"),
        end = as.POSIXct("2022-09-30", tz = "UTC"),
        cc_r = c_closure,
        weather = wethr,
        cultivar_sus = cultivar_sus
      )

      sowing_date <- as.numeric(as.POSIXct("2022-03-31", tz = "UTC"))
      epidemic_onset_map <- (epidemic_onset_map - sowing_date) / (3600 * 24)

    # Output file name and folder
    output_path <- 
      here::here("data/Predicted_epidemic_onset",
                 platform_dir)

    if(dir.exists(output_path) == FALSE){
      dir.create(output_path, recursive = TRUE)}

    # Save the generated epidemic onset map
    terra::writeRaster(epidemic_onset_map, 
                       paste0(output_path,"/Ep_onset_", cultivar_sus, ".tif"))

    # plot the generated epidemic onset map
    terra::plot(epidemic_onset_map)
  }

  # use the previous function for different culvitar susceptbility values
  #(choose the right value for your cultivar)
  cultivar_sus <- seq(from = 7, to = 12, by = 1)

  sapply(cultivar_sus, calc_epidemic_onset_from_image_different_sus)
}

```


## Estimate Earliest Cercopora onset
> **Files Must contain acquisition date in the form of YYYYMMDD, eg 20220615**

```{r}
# loop through platforms with the function
platforms <- c("s2", "s2s", "uas")

for(platform in platforms){
  generate_EO_maps(platforms)
}

```

